Repository ubermag/discretisedfield, pull requests merged in 2024-06, with the labels that each got.

#529 correction `infile` to `input` in wildcard point
  docs/ovf2vtk.ipynb
Labels: documentation, Review effort [1-5]: 1

#527 521 to_vtk
  discretisedfield/field.py
  discretisedfield/tests/test_field.py
Labels: enhancement, Review effort [1-5]: 2, tests

#525 Update pre-commits and pytest configuration
  .pre-commit-config.yaml
  discretisedfield/__init__.py
  discretisedfield/field.py
  discretisedfield/io/__init__.py
  discretisedfield/io/ovf2vtk.py
  discretisedfield/mesh.py
  discretisedfield/plotting/__init__.py
  discretisedfield/plotting/hv.py
  discretisedfield/plotting/k3d_field.py
  discretisedfield/plotting/mpl.py
  discretisedfield/plotting/mpl_field.py
  discretisedfield/tests/test_field.py
  discretisedfield/tools/__init__.py
  discretisedfield/tools/tools.py
  discretisedfield/util/__init__.py
  pyproject.toml
  setup.cfg
  tasks.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3
